#+OPTIONS: timestamp:nil

#+AUTHOR: Vegan i Arvika <via@elis.nu>
#+DATE: <2023-04-25 Tue 12:00+0200>
#+EMAIL: via@hirwing.se
#+TITLE: Arvika Nyheter: Arvika är Sveriges sämsta kommun för djuren?

Publicerat: [[https://www.arvikanyheter.se/2023/04/25/arvika-ar-sveriges-samsta-kommun-for-djuren-8a4f1/][Arvika Nyheter: Arvika är Sveriges sämsta kommun för djuren?]]

Arvika är Sveriges sämsta kommun för djuren? Vad gör kommunen?

Arvika kommun hamnade på delad sista plats i Djurens Rätts ranking
"Djurvänlig kommun". Enligt undersökningen fick Arvika endast 3 poäng av 174
möjliga. Det är en besvikelse för djurvänner och kommuninvånare som vill se
kommunen ta ansvar för en mer hållbar och etisk livsmedelsproduktion.

Vi har tagit en närmare titt på Arvikas svar på enkäten och upptäckte att de
hade hoppat över nästan alla frågor. Detta väcker frågor om kommunens
engagemang i att främja djurvänliga val och miljömässigt hållbara
matvanor. Det är viktigt att vi som kommuninvånare är medvetna om hur våra
beslutsfattare agerar i dessa frågor och att vi ställer krav på våra
kommunala tjänstemän och politiker att ta ansvar för en mer hållbar och etisk
livsmedelsproduktion.

Vi uppmanar Arvika kommun och dess politiker att ta en större roll i att
främja djurvänliga val och miljömässigt hållbara matvanor. Vi vill se tydliga
åtgärder och konkreta planer för att förbättra kommunens resultat i Djurens
Rätts ranking "Djurvänlig kommun". Vi vill också påpeka att grannkommunen Eda
hamnade på plats 106 i samma undersökning, vilket är 144 platser bättre än
Arvika. Detta visar att det är möjligt att göra positiva förändringar och
förbättra placeringen i rankingen.

Vi hoppas att Arvika kommun och dess politiker tar detta på allvar och ser
till att Arvika blir en djurvänligare och mer hållbar kommun för
framtiden. Vi som kommuninvånare har en viktig roll att spela genom att
ställa krav på våra politiker och se till att våra röster hörs i dessa
viktiga frågor.

*Elis & Caroline Hirwing, grundare av mötesplatsen Vegan i Arvika*
