# Disable generated timestamp.
#+OPTIONS: timestamp:nil

#+AUTHOR: Vegan i Arvika <via@elis.nu>
#+DATE: <2023-10-20 Fri 20:30+0200>
#+EMAIL: via@hirwing.se
#+TITLE: Insändare: Arvika kommuns beslut säkerställer barns brist på näring

Publicerat: [[https://www.nwt.se/2023/10/23/nej-till-vegansk-kost-i-skolan-hapnadsvackande-och-tragiskt-8d2d6/][Nya Wermlands-Tidningen: Nej till vegansk kost i skolan:
”Häpnadsväckande och tragiskt”]], [[https://www.arvikanyheter.se/2023/10/24/arvika-kommuns-beslut-sakerstaller-barns-brist-pa-naring-19db1/][Arvika Nyheter: Arvika kommuns beslut
säkerställer barns brist på näring]]

Även skickat till VF.

I ett nyligen fattat beslut har Vård och Omsorgs-nämnden i Arvika kommun
tagit ett beslut om att inte tillåta vegansk kost i skolan. Inte ens för
högstadie- eller gymnasieungdomar.

Motiveringen bakom detta beslut är en irrationell rädsla för att de som äter
vegan-kost inte ska få i sig alla de viktiga näringsämnen som de behöver.

Vi ser ett par problem med detta.

Ingen människa får i sig samtliga näringsämnen från varje måltid och det
finns ett föräldraansvar att se till att barnen får alla näringsämnen. Detta
gäller oavsett vilka etiska värderingar man har eller vilken kosthållning man
väljer.

Veganism är ofta ett starkt etiskt ställningstagande som inte försvinner bara
för att kommunen anser att de inte ska få kost som följer deras etiska
värderingar. Detta leder till stor risk att man får barn som bara petar i
maten eller enbart äter grönsallad. Vilket då säkerställer att de veganska
barnen inte får kompletta måltider och då uppfyller denna näringsbrist som de
är så rädda för.

Det är märkligt att kommunen går emot de nationella riktlinjerna samt
livsmedelsverket rörande skolmat.

I Karlstad kommun så erbjuds vegansk kost från 3 års ålder, detta är så klart
i nära samarbete med föräldrarna. Så att Arvika inte ens kan godkänna det för
gymnasieungdomar, där den äldre gruppen av dem nästan är myndiga är
häpnadsväckande och tragiskt.

*Elis & Caroline Hirwing, grundare av mötesplatsen Vegan i Arvika*
